[paths]
# All paths should end with '/'
media = "./images/"
data = "./gallery_data/"

[media]
thumbnail_size = [ 300, 720 ]

[database]
commit_batch_size = 200

[server]
host = "127.0.0.1"
port = 5000
